<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('pelamars', function (Blueprint $table) {
            $table->string('jenis_jabatan_pekerjaan')->nullable();
            $table->string('lokasi_penempatan_diinginkan')->nullable();
            $table->string('nama_lengkap')->nullable();
            $table->string('alamat_ktp')->nullable();
            $table->string('alamat_domisili')->nullable();
            $table->string('kelurahan')->nullable();
            $table->string('kecamatan')->nullable();
            $table->string('kabupaten_kota')->nullable();
            $table->string('tempat_lahir')->nullable();
            $table->date('tanggal_lahir')->nullable();
            $table->string('jenis_kelamin')->nullable();
            $table->string('no_ktp')->nullable();
            $table->string('foto_ktp')->nullable();
            $table->string('foto_kartu_keluarga')->nullable();
            $table->string('no_whatsapp')->nullable();
            $table->string('no_lain_dihubungi')->nullable();
            $table->string('warga_negara')->nullable();
            $table->string('agama')->nullable();
            $table->string('status_pernikahan')->nullable();
            $table->string('nama_suami_istri')->nullable();
            $table->integer('usia_suami_istri')->nullable();
            $table->string('pekerjaan_suami_istri')->nullable();
            $table->string('alamat_suami_istri')->nullable();
            $table->string('nama_anak1')->nullable();
            $table->string('jk_anak1')->nullable();
            $table->string('ttl_anak1')->nullable();
            $table->string('nama_anak2')->nullable();
            $table->string('jk_anak2')->nullable();
            $table->string('ttl_anak2')->nullable();
            $table->string('nama_anak3')->nullable();
            $table->string('jk_anak3')->nullable();
            $table->string('ttl_anak3')->nullable();
            $table->string('nama_ayah')->nullable();
            $table->integer('usia_ayah')->nullable();
            $table->string('pekerjaan_ayah')->nullable();
            $table->string('alamat_ayah')->nullable();
            $table->string('nama_ibu')->nullable();
            $table->integer('usia_ibu')->nullable();
            $table->string('pekerjaan_ibu')->nullable();
            $table->string('alamat_ibu')->nullable();
            $table->integer('tinggi_badan')->nullable();
            $table->integer('berat_badan')->nullable();
            $table->string('surat_keterangan_sehat')->nullable();
            $table->string('golongan_darah')->nullable();
            $table->string('ukuran_seragam')->nullable();
            $table->string('ukuran_sepatu')->nullable();
            $table->boolean('punya_tato')->nullable();
            $table->boolean('perokok')->nullable();
            $table->text('kesehatan_umum')->nullable();
            $table->text('olahraga_dilakukan')->nullable();
            $table->text('kesehatan_mata')->nullable();
            $table->text('cacat_penyakit_serius')->nullable();
            $table->string('sertifikasi_pelamar')->nullable();
            $table->string('foto_ijazah_terakhir')->nullable();
            $table->string('foto_sertifikat_keahlian1')->nullable();
            $table->string('foto_sertifikat_keahlian2')->nullable();
            $table->text('keahlian_dimiliki')->nullable();
            $table->text('hobby_keahlian_disukai')->nullable();
            $table->text('keterampilan_kerja_disukai')->nullable();
            $table->text('peralatan_kerja_dikuasai')->nullable();
            $table->text('program_komputer_dikuasai')->nullable();
            $table->text('keahlian_ingin_dicapai')->nullable();
            $table->text('jenis_bahasa_dikuasai')->nullable();
            $table->text('kendaraan_dikuasai')->nullable();
            $table->string('sim_dimiliki')->nullable();
            $table->text('rencana_target_masa_depan')->nullable();
            $table->boolean('suka_berorganisasi')->nullable();
            $table->text('organisasi_diikuti')->nullable();
            $table->string('pengalaman_kerja1_perusahaan')->nullable();
            $table->string('pengalaman_kerja1_alamat')->nullable();
            $table->string('pengalaman_kerja1_masa_kerja')->nullable();
            $table->string('pengalaman_kerja1_jabatan')->nullable();
            $table->decimal('pengalaman_kerja1_gaji_awal', 15, 2)->nullable();
            $table->decimal('pengalaman_kerja1_gaji_akhir', 15, 2)->nullable();
            $table->text('pengalaman_kerja1_alasan_berhenti')->nullable();
            $table->string('pengalaman_kerja2_perusahaan')->nullable();
            $table->string('pengalaman_kerja2_alamat')->nullable();
            $table->string('pengalaman_kerja2_masa_kerja')->nullable();
            $table->string('pengalaman_kerja2_jabatan')->nullable();
            $table->decimal('pengalaman_kerja2_gaji_awal', 15, 2)->nullable();
            $table->decimal('pengalaman_kerja2_gaji_akhir', 15, 2)->nullable();
            $table->text('pengalaman_kerja2_alasan_berhenti')->nullable();
            $table->text('tanggungan_ekonomi')->nullable();
            $table->decimal('nilai_tanggungan_perbulan', 15, 2)->nullable();
            $table->boolean('bersedia_lembur')->nullable();
            $table->text('alasan_lembur')->nullable();
            $table->boolean('bersedia_dipindahkan_bagian_lain')->nullable();
            $table->text('alasan_dipindahkan_bagian_lain')->nullable();
            $table->boolean('bersedia_ikut_pembinaan_pelatihan')->nullable();
            $table->boolean('bersedia_penuhi_peraturan_pengamanan')->nullable();
            $table->boolean('bersedia_dipindahkan_luar_daerah')->nullable();
            $table->decimal('gaji_diharapkan', 15, 2)->nullable();
            $table->decimal('batas_gaji_minimum', 15, 2)->nullable();
            $table->text('fasilitas_diharapkan')->nullable();
            $table->date('kapan_bisa_mulai_bekerja')->nullable();
            $table->text('motivasi_utama_bekerja')->nullable();
            $table->text('alasan_diterima_perusahaan')->nullable();
            $table->text('hal_lain_disampaikan')->nullable();
            $table->boolean('pernah_ikut_beladiri')->nullable();
            $table->string('sertifikat_beladiri')->nullable();
            $table->string('foto_full_body')->nullable();
            $table->boolean('pernyataan_kebenaran_dokumen')->nullable();
            $table->boolean('pernyataan_lamaran_kerja')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('pelamars', function (Blueprint $table) {
            $table->dropColumn([
                'jenis_jabatan_pekerjaan',
                'lokasi_penempatan_diinginkan',
                'nama_lengkap',
                'alamat_ktp',
                'alamat_domisili',
                'kelurahan',
                'kecamatan',
                'kabupaten_kota',
                'tempat_lahir',
                'tanggal_lahir',
                'jenis_kelamin',
                'no_ktp',
                'foto_ktp',
                'foto_kartu_keluarga',
                'no_whatsapp',
                'no_lain_dihubungi',
                'warga_negara',
                'agama',
                'status_pernikahan',
                'nama_suami_istri',
                'usia_suami_istri',
                'pekerjaan_suami_istri',
                'alamat_suami_istri',
                'nama_anak1',
                'jk_anak1',
                'ttl_anak1',
                'nama_anak2',
                'jk_anak2',
                'ttl_anak2',
                'nama_anak3',
                'jk_anak3',
                'ttl_anak3',
                'nama_ayah',
                'usia_ayah',
                'pekerjaan_ayah',
                'alamat_ayah',
                'nama_ibu',
                'usia_ibu',
                'pekerjaan_ibu',
                'alamat_ibu',
                'tinggi_badan',
                'berat_badan',
                'surat_keterangan_sehat',
                'golongan_darah',
                'ukuran_seragam',
                'ukuran_sepatu',
                'punya_tato',
                'perokok',
                'kesehatan_umum',
                'olahraga_dilakukan',
                'kesehatan_mata',
                'cacat_penyakit_serius',
                'sertifikasi_pelamar',
                'foto_ijazah_terakhir',
                'foto_sertifikat_keahlian1',
                'foto_sertifikat_keahlian2',
                'keahlian_dimiliki',
                'hobby_keahlian_disukai',
                'keterampilan_kerja_disukai',
                'peralatan_kerja_dikuasai',
                'program_komputer_dikuasai',
                'keahlian_ingin_dicapai',
                'jenis_bahasa_dikuasai',
                'kendaraan_dikuasai',
                'sim_dimiliki',
                'rencana_target_masa_depan',
                'suka_berorganisasi',
                'organisasi_diikuti',
                'pengalaman_kerja1_perusahaan',
                'pengalaman_kerja1_alamat',
                'pengalaman_kerja1_masa_kerja',
                'pengalaman_kerja1_jabatan',
                'pengalaman_kerja1_gaji_awal',
                'pengalaman_kerja1_gaji_akhir',
                'pengalaman_kerja1_alasan_berhenti',
                'pengalaman_kerja2_perusahaan',
                'pengalaman_kerja2_alamat',
                'pengalaman_kerja2_masa_kerja',
                'pengalaman_kerja2_jabatan',
                'pengalaman_kerja2_gaji_awal',
                'pengalaman_kerja2_gaji_akhir',
                'pengalaman_kerja2_alasan_berhenti',
                'tanggungan_ekonomi',
                'nilai_tanggungan_perbulan',
                'bersedia_lembur',
                'alasan_lembur',
                'bersedia_dipindahkan_bagian_lain',
                'alasan_dipindahkan_bagian_lain',
                'bersedia_ikut_pembinaan_pelatihan',
                'bersedia_penuhi_peraturan_pengamanan',
                'bersedia_dipindahkan_luar_daerah',
                'gaji_diharapkan',
                'batas_gaji_minimum',
                'fasilitas_diharapkan',
                'kapan_bisa_mulai_bekerja',
                'motivasi_utama_bekerja',
                'alasan_diterima_perusahaan',
                'hal_lain_disampaikan',
                'pernah_ikut_beladiri',
                'sertifikat_beladiri',
                'foto_full_body',
                'pernyataan_kebenaran_dokumen',
                'pernyataan_lamaran_kerja',
            ]);
        });
    }
};